#!/bin/bash

device="SynPS/2 Synaptics TouchPad"
state=$(xinput list-props "$device" | grep "Device Enabled" | grep -o "[01]$")

if [ $state == '1' ];then
  xinput --disable "$device"
  xdotool mousemove 0 1080
else
  xinput --enable "$device"
fi
